### ISSUE TITLE
Console Permissions Restructure

### ISSUE THREAD

**Issue by runesage** [eccentricdevotion/TARDIS#634]
### Describe the feature request

With more and more consoles being added it can be cumbersome to do manual permissions for each console. I wanted to propose restructuring the permissions structure for consoles similiar to how rooms/presets are done. Maybe something like

tardis.console.deluxe
tardis.console.factory
tardis.console.steampunk

This would also allow admins to do wildcard perms on the consoles with tardis.console.*

### Describe alternatives you've considered

n/a

**Comment by eccentricdevotion** [comment]
Less of a change to add a `*` node, hope that suits... Build 2438

```
permissions:
  tardis.console.*:
    description: Allow players to build all TARDIS types.
    children:
      tardis.ars: true
      tardis.bigger: true
      tardis.cave: true
      tardis.copper: true
      tardis.coral: true
      tardis.custom: true
      tardis.delta: true
      tardis.deluxe: true
      tardis.division: true
      tardis.eleventh: true
      tardis.ender: true
      tardis.factory: true
      tardis.legacy_bigger: true
      tardis.legacy_budget: true
      tardis.legacy_deluxe: true
      tardis.legacy_eleventh: true
      tardis.legacy_redstone: true
      tardis.master: true
      tardis.plank: true
      tardis.pyramid: true
      tardis.redstone: true
      tardis.rotor: true
      tardis.steampunk: true
      tardis.thirteenth: true
      tardis.tom: true
      tardis.twelfth: true
      tardis.war: true
      tardis.weathered: true
    default: op
```
