### ISSUE TITLE
Difficulty 

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#754]
### Describe the feature request

**Describe the feature request**
clean cut difference between med and hard modes

currently the main difference i can see between the med and hard mode is the crafting recipe. what i would like see is it to effect the players day to day use of the Tardis

Crafting stays the same 

Circuits 
Easy Optimal in control
Med Required in control 
hard Required in Control

Disks
Easy Optimal
Med Optimal
Hard Required

Area disk can be crafted

Area Disks can be saved by standing in the area and clicking air with the disk

### Describe alternatives you've considered

New Config settings

Circuits   True / false     Requires circuits to be in the advanced console
Damage True / false     Circuits take damage when used 
Disk   True / false          Disks are required in advance console

**Comment by doctormysterio12** [comment]
I like your alternative! I'd prefer the difficulty to be split between the 3 aspects, as I don't like how Player Disks are handled, so being able to use binds or /travel player whilst having circuits enabled would be great

**Comment by ToppanaFIN** [comment]
I forgot this was here, but I like what Air suggests with medium, since currently its either easy or use disks for everything. I really like the circuit aspect of the plugin but dont like the usage of disks as its a bit of a hassle in my opinion.

**Comment by roberestarkk** [comment]
I personally most prefer Difficulty as a meta-concept in games...

Just make the individual aspects impacted by 'difficulty level' directly configurable, and have certain presets for those groups of configurable settings to represent the Author's vision of "Easy" vs. "Hard"...

That way, people who like circuits but not disks can configure it that way, people who like disks but not circuits can configure it that way, people who like both, or neither... 
Any combination you think best suits how difficult (or not) you want it to be, can be done!

**Comment by Airomis** [comment]
I agree! I been hoping for this idea to get some attention for years

**Comment by doctormysterio12** [comment]
It would be cool if saves had 3 separate difficulties

Saves
Easy - commands work and add to the memory
medium - a memory circuit is required to allow saves to be used with commands
hard - save disks are required

Also it appears that currently, when the circuits are broken, the signs like the chameleon circuit and save sign still work without a memory circuit, but the warning saying so does appear when accessing through the control sign

**Comment by eccentricdevotion** [comment]
The chameleon sign / GUI uses the `Chameleon` circuit, not the `Memory` circuit... regardless both instances have code for checking circuits, so it _should_ be working.

I'm heading down the path of _not_ having easy/medium/hard modes (except easy/hard recipes) and going with more config options:

```yaml
difficulty:
  crafting: [easy|hard]
  circuits: [true|false]
  disks: [true|false]
  disk_in_hand_for_write: [true|false] # must have disk in hand when using /tardis save and disks is true
  tardis_locator: [true|false] # must use locator instead of  /tardis find
  stattenheim_remote: [true|false] # must use remote instead of  /tardis comehere
  biome_reader: [true|false] # allow the biome reader to save biome disks and use them if using the /ttravel biome command
```
