### ISSUE TITLE
Using planets.yml to load worlds with invalid game rules disables the plugin

### ISSUE THREAD

**Issue by Tarluin** [eccentricdevotion/TARDIS#805]
### Describe the bug

[17:21:01 INFO]: [TARDIS] Could not load world 'spawn'! GameRule cannot be null

```
  spawn:
    enabled: true
    resource_pack: default
    gamemode: SURVIVAL
    time_travel: false
    world_type: FLAT
    environment: NORMAL
    void: true
    generator: TARDIS:void
    gamerules:
      doWeatherCycle: false
      doDaylightCycle: false
      doWardenSpawning: false
      keepInventory: true
      doFireTick: false
      doMobSpawn: false
    keep_spawn_in_memory: false
    allow_portals: false
    alias: Spawn
    icon: SMOOTH_QUARTZ
    difficulty: PEACEFUL
```

ran the file thru a yaml validator and it said it was all good

sidenote, there used to be a file you could make that defined the world guard flags to use, does that still exists? I am using slime fun also and I want them to be able to use the smelter which requires a block to be on fire.

### To Reproduce

install Tardis plugin
place this in planets.yml:

```
  spawn:
    enabled: true
    resource_pack: default
    gamemode: SURVIVAL
    time_travel: false
    world_type: FLAT
    environment: NORMAL
    void: true
    generator: TARDIS:void
    gamerules:
      doWeatherCycle: false
      doDaylightCycle: false
      doWardenSpawning: false
      keepInventory: true
      doFireTick: false
      doMobSpawn: false
    keep_spawn_in_memory: false
    allow_portals: false
    alias: Spawn
    icon: SMOOTH_QUARTZ
    difficulty: PEACEFUL
```

Boot server.

### Log files

[17:21:01 INFO]: [TARDIS] Could not load world 'spawn'! GameRule cannot be null

### '/tardis version' output

> [17:21:22 INFO]: [TARDIS] Server version: git-Paper-408 (MC: 1.20.4)
> [17:21:22 INFO]: [TARDIS] TARDIS version: 5.3.0-b2778
> [17:21:22 INFO]: [TARDIS] Vault version: 1.7.3-CMI
> [17:21:22 INFO]: [TARDIS] WorldGuard version: 7.0.9+5934e49
> [17:21:22 INFO]: [TARDIS] PlaceholderAPI version: 2.11.5
> [17:21:22 INFO]: [TARDIS] Checking for new TARDIS builds...
> [17:21:22 INFO]: [TARDIS] A new version is available, but requires a server update to 1.20.4

Last line is odd, I'm using 1.20.4 paper server...
