### ISSUE TITLE
Time Rotors for all original TARDISes

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#826]
Add more time rotors.

We have the 1st and12th's, but no 10th, etc.

**Comment by eccentricdevotion** [comment]
We have 1st, 9/10th, 11th and 12th
https://tardis.pages.dev/time-rotor

**Comment by doctormysterio12** [comment]
why not add an api for custom rotors similar to custom models and allow us to put our own in? 

what's the requirements? an "off" mode, then an integer of how many stages of animation? Could that be configurable?

Also, the time rotor could be linked to the tardis flight, not the handbrake, so the animation would be smoother to stop when the Tardis lands, rather than depending on when the handbrake is applied

**Comment by eccentricdevotion** [comment]
Example _custom_time_rotors.yml_ config entry:

```
classic:
  # assets/minecraft/models/item/light_gray_dye.json
  # must be higher than 10000009
  off_custom_model_data: 10000010
  # the material of the animated rotor item
  # animation states start at "custom_model_data": 1021
  # set in assets/minecraft/models/item/[animated_material].json
  # must be unique for each rotor
  animated_material: YELLOW_DYE
  # a comma separated list of frame numbers where the
  # number is added to the starting animation frame to
  # get the custom_model_data predicate e.g. 1021 + 3 = 1024
  animation_sequence: 0,1,2,3,4,5,6,7
  # frame rate in ticks
  frame_rate: 6
```
